import Usuario from "./usuario.model";
import Cuenta_Acceso from "./cuenta_acceso.model";
import Persona from "./persona.model";
import Producto from "./producto.model";
import Categoria from "./categoria.model";
import TProducto from "./tipo_producto.model";
import Ambulancia from "./ambulancia.model";
import Unidad_Medida from './unidad_medida.model'; 
import Producto_Ambulancia from "./producto_ambulancia";
import Registro_Producto from "./registro_producto";
import Trabaja from "./trabaja.model";
import Reporte from './reporte.model';
export {Usuario, Cuenta_Acceso, Persona, Producto, TProducto, Categoria, Ambulancia, Unidad_Medida, Producto_Ambulancia, Registro_Producto, Trabaja, Reporte};